### ISSUE TITLE
WebIO.Asset Seems not working

### ISSUE THREAD

**Issue by alirezamecheng** [JuliaGizmos/WebIO.jl#331]
Hello, 
It seems that the `Asset` function doesn't do anything.
the content of css.css file 
```css
.class1{
    background: gray;
}
.class2{
    background-color: blue
}
.class3{
    background-color: brown;
}
```
The julia code:
```julia 
using Blink
using WebIO

w = Window()
WebIO.Asset("./css.css")
page = node(:div,
            node(:h1,"title",class="class1"),
            node(:p, "this is some text",class="class2"),
            node(:hr),
            node(:p, "some random text. some random text. some random text. some random text. ",class = "class3")
)
body!(w,page)
```
The output is : 
![image](https://user-images.githubusercontent.com/29999507/62043519-d2129000-b215-11e9-93d0-3067f7490877.png)

Am I missing something?
